export { Light } from './light'
export { Switch } from './switch'
export { Lock } from './lock'
export { Thermostat } from './thermostat'
export { Vacuum } from './vacuum'
export { Speaker } from './speaker'
