export const deviceList = [
  {
    device_id: '646676275e1d7fa4b72610d3ce14a7f7',
    area_id: null,
    name: 'Sun',
    friendly_name: 'Sun',
    entities: [],
  },
  {
    device_id: 'f64cb397805e1e9bf80efa4d6e5eeb2a',
    area_id: 'kitchen',
    name: 'Kitchen',
    friendly_name: 'Homepod Mini kitchen',
    entities: ['Homepod Mini kitchen'],
  },
  {
    device_id: '3552b8ee2da52918a93688ceba307df1',
    area_id: 'living_room',
    name: 'Living Room (2)',
    friendly_name: 'Apple TV',
    entities: ['Apple TV'],
  },
  {
    device_id: '055eb8fa26a4bfad7e8992410ad075b0',
    area_id: 'living_room',
    name: 'Living Room (3)',
    friendly_name: 'Homepod L',
    entities: ['Homepod L'],
  },
  {
    device_id: 'e96caf02bb568ab643554bb95c457efe',
    area_id: 'living_room',
    name: 'Living Room',
    friendly_name: 'Homepod R',
    entities: ['Homepod R'],
  },
  {
    device_id: '2b27767ee01959fc10c6d58dedd64ceb',
    area_id: 'living_room',
    name: 'Texas Instruments Coordinator',
    friendly_name: 'Texas Instruments Coordinator',
    entities: [],
  },
  {
    device_id: '0384e083ab7c7cd1300b11d2958bc12d',
    area_id: null,
    name: 'govee',
    friendly_name: 'govee',
    entities: [],
  },
  {
    device_id: 'e47d99aae59c29200828536dc821c681',
    area_id: 'office',
    name: 'Office corner lamp',
    friendly_name: 'Office corner lamp',
    entities: ['Office corner lamp'],
  },
  {
    device_id: '5bdb8afc69daf21d68777bd1f28ae514',
    area_id: 'living_room',
    name: 'hci1 (DC:A6:32:D8:6F:A2)',
    friendly_name: 'hci1 (DC:A6:32:D8:6F:A2)',
    entities: [],
  },
  {
    device_id: 'f429ce1ff2390301255fe493d1f29b3a',
    area_id: null,
    name: 'Marks iPhone 15 Pro',
    friendly_name: 'Marks iPhone 15 Pro',
    entities: [
      'Marks iPhone 15 Pro Battery Level',
      'Marks iPhone 15 Pro SIM 2',
      'Marks iPhone 15 Pro SIM 1',
      'Marks iPhone 15 Pro Battery State',
      'Marks iPhone 15 Pro BSSID',
      'Marks iPhone 15 Pro Last Update Trigger',
      'Marks iPhone 15 Pro Geocoded Location',
      'Marks iPhone 15 Pro Storage',
      'Marks iPhone 15 Pro Connection Type',
      'Marks iPhone 15 Pro SSID',
      'Marks iPhone 15 Pro Activity',
      'Marks iPhone 15 Pro Focus',
      'Marks iPhone 15 Pro Distance',
      'Marks iPhone 15 Pro Floors Ascended',
      'Marks iPhone 15 Pro Floors Descended',
      'Marks iPhone 15 Pro Steps',
      'Marks iPhone 15 Pro Average Active Pace',
    ],
  },
  {
    device_id: 'c8cb4f4595da1cb2f76dc8e3696212c3',
    area_id: 'office',
    name: 'Smart Plug-in Unit',
    friendly_name: 'Office closet light',
    entities: ['Office closet light', 'Office closet light'],
  },
  {
    device_id: '8d19dd9078b7536702584501194d2309',
    area_id: 'office',
    name: 'Office',
    friendly_name: 'Homepod mini office',
    entities: ['Homepod mini'],
  },
  {
    device_id: '84eebc553758738e85034acc9c89cd3e',
    area_id: 'living_room',
    name: 'eero',
    friendly_name: 'eero',
    entities: [],
  },
  {
    device_id: '4df24d392a1046efb9e7fcc8b8d61469',
    area_id: 'living_room',
    name: 'Living Room',
    friendly_name: 'Living Room',
    entities: [
      'Living Room Occupancy',
      'Living Room',
      'Living Room Temperature',
      'Living Room Humidity',
      'Living Room Air quality index',
      'Living Room VOCs',
      'Living Room Carbon dioxide',
      'Living Room',
      'Living Room',
    ],
  },
  {
    device_id: 'dc8649c80795f952a3f73e0e78c4f66c',
    area_id: 'bedroom',
    name: 'SmartSensor',
    friendly_name: 'SmartSensor',
    entities: ['SmartSensor Occupancy', 'SmartSensor Temperature'],
  },
  {
    device_id: '93616a080352fe9a80413176301a7d41',
    area_id: null,
    name: 'Dyson',
    friendly_name: 'Dyson',
    entities: [],
  },
  {
    device_id: '0c69894c457bfab6410a3356c697be0b',
    area_id: 'bedroom',
    name: 'Bedroom',
    friendly_name: 'Bedroom',
    entities: [
      'Bedroom',
      'Bedroom Humidity',
      'Bedroom Temperature',
      'Bedroom Volatile Organic Compounds Index',
      'Bedroom PM 2.5',
      'Bedroom PM 10',
      'Bedroom Nitrogen Dioxide Index',
      'Bedroom HCHO',
      'Bedroom',
    ],
  },
  {
    device_id: '87017a31ddea191485435c78ba339194',
    area_id: null,
    name: 'Eight Sleep Integration',
    friendly_name: 'Eight Sleep Integration',
    entities: [],
  },
  {
    device_id: '6be01f4eab91567bff38fb2e6b8a59eb',
    area_id: 'bedroom',
    name: "hello@marklyck.com's Eight Sleep",
    friendly_name: "hello@marklyck.com's Eight Sleep",
    entities: [
      'Eight Sleep Room Temperature',
      'Eight Sleep Need Priming',
      'Eight Sleep Is Priming',
      'Eight Sleep Has Water',
      'Eight Sleep Last Prime',
    ],
  },
  {
    device_id: '76078057accfb08941605ffcae7cecf3',
    area_id: 'bedroom',
    name: "Grace's Eight Sleep Side",
    friendly_name: "Grace's Eight Sleep Side",
    entities: [],
  },
  {
    device_id: '683dbf1f559bc5fddd988de300e9c66c',
    area_id: 'bedroom',
    name: "Mark's Eight Sleep Side",
    friendly_name: "Mark's Eight Sleep Side",
    entities: [],
  },
  {
    device_id: 'c477e93a9818a962f576729140d9c517',
    area_id: null,
    name: 'hci0 (00:E0:4C:88:16:03)',
    friendly_name: 'hci0 (00:E0:4C:88:16:03)',
    entities: [],
  },
  {
    device_id: '5b48b95b145e634940c3b75979633f14',
    area_id: 'office',
    name: 'Aranet4 23B35',
    friendly_name: 'Aranet4 23B35',
    entities: [
      'Aranet4 23B35 Temperature',
      'Aranet4 23B35 Humidity',
      'Aranet4 23B35 Pressure',
      'Aranet4 23B35 Carbon Dioxide',
    ],
  },
  {
    device_id: '273a3a9cdb83845f0dc773f69877dfc2',
    area_id: 'office',
    name: 'H61E0',
    friendly_name: 'Desk light',
    entities: ['Desk light'],
  },
  {
    device_id: 'b38846d1883c20045a0e07033e9bf2a0',
    area_id: 'office',
    name: 'Presence-Sensor-FP2-2B45',
    friendly_name: 'Presence-Sensor-FP2-2B45',
    entities: [
      'Presence-Sensor-FP2-2B45 Light Sensor Light Level',
      'Desk presence',
      'Office presence',
    ],
  },
  {
    device_id: '0a935ee16f42bdb7f5f855978d0168f3',
    area_id: null,
    name: 'LED Strip Light M1',
    friendly_name: 'LED Strip Light M1',
    entities: ['LED Strip Light M1'],
  },
  {
    device_id: '28fc92e7059516a0d0f1d30475bdd391',
    area_id: null,
    name: 'NL67',
    friendly_name: 'Nursery lamp',
    entities: [],
  },
  {
    device_id: '98c962f84b3db727ab801a5319b903c1',
    area_id: 'office',
    name: 'Flexispot E6',
    friendly_name: 'desk',
    entities: [
      'Desk',
      'Desk Height',
      'Preset 1',
      'Preset 2',
      'Preset 3',
      'M',
      '(wake up)',
      'Desk Standing',
      'Desk Sitting',
    ],
  },
  {
    device_id: '1c1cf68cf327ed55e467ab7c21b00034',
    area_id: 'nursery',
    name: 'Presence-Sensor-FP2-E017',
    friendly_name: 'Presence-Sensor-FP2-E017',
    entities: [
      'Presence-Sensor-FP2-E017 Light Sensor Light Level',
      'Nursery Presence',
      'Nursery Presence',
      'Entrance Presence',
      'Hallway Presence',
      'Presence-Sensor-FP2-E017 Presence Sensor 5',
    ],
  },
  {
    device_id: 'd5f2f693dd7300c3da12fa1801e6ee2b',
    area_id: 'bedroom',
    name: 'VOCOlinc-VHI-1fea6c',
    friendly_name: 'VOCOLinc humidifier',
    entities: [
      'VOCOLinc humidifier Current Humidity',
      'VOCOLinc humidifier Humidifier',
      'VOCOLinc humidifier Mood Light',
    ],
  },
  {
    device_id: '64a5184a5d7f46deeb05264b3e699d11',
    area_id: null,
    name: 'Alfred',
    friendly_name: 'Alfred',
    entities: [
      'Alfred Area cleaned',
      'Alfred Cleaning duration',
      'Alfred Total area cleaned',
      'Alfred Total cleaning duration',
      'Alfred Total cleanings',
      'Alfred',
      'Alfred Map',
    ],
  },
  {
    device_id: '621ecb5eb6adf4f269b9701331cf165e',
    area_id: null,
    name: "Mark's Eight Sleep Side",
    friendly_name: "Mark's Eight Sleep Side",
    entities: [
      "Mark's Bed Presence",
      "Mark's Sleep Fitness Score",
      "Mark's Sleep Quality Score",
      "Mark's Sleep Routine Score",
      "Mark's Time Slept",
      "Mark's Heart Rate",
      "Mark's HRV",
      "Mark's Breath Rate",
      "Mark's Bed Temperature",
      "Mark's Sleep Stage",
      "Mark's Next Alarm",
      "Mark's Bed State Type",
      "Mark's Previous Presence Start",
      "Mark's Previous Presence End",
      "Mark's Bed State",
    ],
  },
  {
    device_id: '066f0e705abbc0c1c69aa47cb2d5db6f',
    area_id: null,
    name: "Grace's Eight Sleep Side",
    friendly_name: "Grace's Eight Sleep Side",
    entities: [
      "Grace's Bed Presence",
      "Grace's Sleep Fitness Score",
      "Grace's Sleep Quality Score",
      "Grace's Sleep Routine Score",
      "Grace's Time Slept",
      "Grace's Heart Rate",
      "Grace's HRV",
      "Grace's Breath Rate",
      "Grace's Bed Temperature",
      "Grace's Sleep Stage",
      "Grace's Next Alarm",
      "Grace's Bed State Type",
      "Grace's Previous Presence Start",
      "Grace's Previous Presence End",
      "Grace's Bed State",
    ],
  },
  {
    device_id: 'f646801fcd074031623c79c2cd93a5f8',
    area_id: 'living_room',
    name: 'Philips hue',
    friendly_name: 'Philips hue',
    entities: [],
  },
  {
    device_id: '75c8c9b640d18fe2c57f794435f73c22',
    area_id: 'living_room',
    name: 'Bedroom',
    friendly_name: 'Bedroom',
    entities: [],
  },
  {
    device_id: '893a9e8aad9f4cb997f5ae420498706d',
    area_id: null,
    name: 'Mark Lyck’s iPad',
    friendly_name: 'Mark Lyck’s iPad',
    entities: [
      'Mark Lyck’s iPad Activity',
      'Mark Lyck’s iPad Battery Level',
      'Mark Lyck’s iPad Battery State',
      'Mark Lyck’s iPad Connection Type',
      'Mark Lyck’s iPad Geocoded Location',
      'Mark Lyck’s iPad Focus',
      'Mark Lyck’s iPad Last Update Trigger',
      'Mark Lyck’s iPad Storage',
      'Mark Lyck’s iPad SSID',
      'Mark Lyck’s iPad BSSID',
    ],
  },
  {
    device_id: 'ffcd4a7420d37e7fdc7a99dd5cb97028',
    area_id: null,
    name: 'Mark’s iPad',
    friendly_name: 'Mark’s iPad',
    entities: [
      'Mark’s iPad Battery State',
      'Mark’s iPad Battery Level',
      'Mark’s iPad SIM 1',
      'Mark’s iPad Last Update Trigger',
      'Mark’s iPad Geocoded Location',
      'Mark’s iPad Storage',
      'Mark’s iPad BSSID',
      'Mark’s iPad SSID',
      'Mark’s iPad Connection Type',
      'Mark’s iPad Activity',
      'Mark’s iPad Focus',
    ],
  },
  {
    device_id: '83b38a819fdee86fc0ace5b57bdd4a4d',
    area_id: 'garage',
    name: 'Lyck',
    friendly_name: 'tesla_model_y',
    entities: [
      'tesla_model_y Battery level',
      'tesla_model_y Battery range',
      'tesla_model_y Charge',
      'tesla_model_y Charge cable lock',
      'tesla_model_y Charge current',
      'tesla_model_y Charge energy added',
      'tesla_model_y Charge limit',
      'tesla_model_y Charge port door',
      'tesla_model_y Charger power',
      'tesla_model_y Charging',
      'tesla_model_y Climate',
      'tesla_model_y Defrost mode',
      'tesla_model_y Distance to arrival',
      'tesla_model_y Flash lights',
      'tesla_model_y Frunk',
      'tesla_model_y Homelink',
      'tesla_model_y Honk horn',
      'tesla_model_y Inside temperature',
      'tesla_model_y Keyless driving',
      'tesla_model_y Lock',
      'tesla_model_y Media player',
      'tesla_model_y Outside temperature',
      'tesla_model_y Play fart',
      'tesla_model_y Seat heater left',
      'tesla_model_y Seat heater rear center',
      'tesla_model_y Seat heater rear left',
      'tesla_model_y Seat heater rear right',
      'tesla_model_y Seat heater right',
      'tesla_model_y Sentry mode',
      'tesla_model_y Shift state',
      'tesla_model_y Speed',
      'tesla_model_y Speed limit',
      'tesla_model_y Status',
      'tesla_model_y Steering wheel heater',
      'tesla_model_y Time to arrival',
      'tesla_model_y Traffic delay',
      'tesla_model_y Trunk',
      'tesla_model_y User present',
      'tesla_model_y Valet mode',
      'tesla_model_y Vent windows',
      'tesla_model_y Wake',
    ],
  },
]
